#!/usr/bin/env python3
"""
Enhanced BMAD Automated Spec Generator with Markdown Config Support

This script automates the BMAD project planning process by integrating with the 
Claude-code-SDK and interacting with the Claude-code-CLI using advanced hook patterns.
Now supports Markdown configuration files generated by the PrompEnhancer agent.

Key features:
- Markdown config file parsing (initProject.md)
- BMAD-METHOD installation and initialization
- Enhanced logging and monitoring
- Better error handling and fallbacks
- Structured hook data processing
- Decision audit trail
- Performance metrics
"""

import asyncio
import json
import logging
import os
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional, List

from claude_code_sdk import ClaudeSDKClient, ClaudeCodeOptions

# --- Configuration ---

# Set up structured logging
class BMadLogger:
    def __init__(self, log_file: str = "bmad_decisions.log"):
        self.log_file = Path(log_file)
        self.setup_logging()
    
    def setup_logging(self):
        """Setup structured logging with file and console output"""
        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
            handlers=[
                logging.FileHandler(self.log_file),
                logging.StreamHandler(sys.stderr)
            ]
        )
        self.logger = logging.getLogger("bmad_automator")
    
    def log_decision(self, hook_data: Dict[str, Any], decision: str, reasoning: str, execution_time: float):
        """Log decision with full context for audit trail"""
        decision_record = {
            "timestamp": datetime.now().isoformat(),
            "session_id": hook_data.get("session_id"),
            "hook_event": hook_data.get("hook_event_name"),
            "tool_name": hook_data.get("tool_name"),
            "decision": decision,
            "reasoning": reasoning,
            "execution_time_seconds": execution_time,
            "cwd": hook_data.get("cwd")
        }
        
        self.logger.info(f"DECISION: {json.dumps(decision_record, indent=2)}")
        
        # Also save to structured log file
        decisions_file = Path("bmad_decisions.jsonl")
        with open(decisions_file, "a") as f:
            f.write(json.dumps(decision_record) + "\n")

    def log_bmad_installation(self, install_path: str, success: bool, details: str):
        """Log BMAD installation attempts"""
        install_record = {
            "timestamp": datetime.now().isoformat(),
            "event": "bmad_installation",
            "install_path": install_path,
            "success": success,
            "details": details
        }
        
        self.logger.info(f"BMAD_INSTALL: {json.dumps(install_record, indent=2)}")
        
        # Also save to structured log file
        decisions_file = Path("bmad_decisions.jsonl")
        with open(decisions_file, "a") as f:
            f.write(json.dumps(install_record) + "\n")

# Initialize logger
bmad_logger = BMadLogger()

# --- Markdown Config Parser ---

class MarkdownConfigParser:
    """Parse project configuration from Markdown files generated by PrompEnhancer agent"""
    
    def __init__(self, md_file_path: str):
        self.md_file_path = Path(md_file_path)
        self.config = {}
    
    def parse(self) -> Dict[str, Any]:
        """Parse the Markdown file and extract project configuration"""
        if not self.md_file_path.exists():
            bmad_logger.logger.error(f"Markdown config file not found: {self.md_file_path}")
            raise FileNotFoundError(f"Config file not found: {self.md_file_path}")
        
        try:
            content = self.md_file_path.read_text(encoding='utf-8')
            bmad_logger.logger.info(f"Parsing Markdown config from {self.md_file_path}")
            
            # Parse different sections
            self.config = {
                "project_details": self._parse_project_details(content),
                "constraints": self._parse_constraints(content),
                "technical_requirements": self._parse_technical_requirements(content),
                "bmad_settings": self._parse_bmad_settings(content),
                "metadata": {
                    "source_file": str(self.md_file_path),
                    "parsed_at": datetime.now().isoformat()
                }
            }
            
            bmad_logger.logger.info(f"Successfully parsed Markdown config: {self.config['project_details'].get('name', 'Unnamed Project')}")
            return self.config
            
        except Exception as e:
            bmad_logger.logger.error(f"Error parsing Markdown config: {e}")
            raise
    
    def _parse_project_details(self, content: str) -> Dict[str, Any]:
        """Extract project details from Markdown content"""
        details = {}
        
        # Extract project name from title
        title_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
        if title_match:
            details["name"] = title_match.group(1).strip()
        
        # Extract description from Project Overview section
        overview_match = re.search(r'##\s+Project\s+Overview\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if overview_match:
            details["description"] = overview_match.group(1).strip()
        
        # Extract goals
        goals_match = re.search(r'##\s+Goals?\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if goals_match:
            goals_text = goals_match.group(1).strip()
            # Extract bullet points
            goals = re.findall(r'[-*]\s+(.+)', goals_text)
            details["goals"] = goals
        
        return details
    
    def _parse_constraints(self, content: str) -> Dict[str, Any]:
        """Extract project constraints from Markdown content"""
        constraints = {}
        
        # Extract budget information
        budget_match = re.search(r'##\s+Budget\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if budget_match:
            budget_text = budget_match.group(1)
            
            # Extract total budget
            total_match = re.search(r'\$?([\d,]+)', budget_text)
            if total_match:
                total_str = total_match.group(1).replace(',', '')
                constraints["budget"] = {"total_usd": int(total_str)}
            
            # Extract timeline
            timeline_match = re.search(r'(\d+)\s*weeks?', budget_text, re.IGNORECASE)
            if timeline_match:
                if "budget" not in constraints:
                    constraints["budget"] = {}
                constraints["budget"]["timeline_weeks"] = int(timeline_match.group(1))
        
        # Extract technical constraints
        tech_match = re.search(r'##\s+Technical\s+Constraints\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if tech_match:
            tech_text = tech_match.group(1)
            
            # Extract compute resources
            compute_resources = []
            compute_matches = re.findall(r'[-*]\s+(.+(?:CPU|RAM|GPU|Memory|Storage).+)', tech_text, re.IGNORECASE)
            constraints["compute_resources"] = compute_matches
        
        # Extract tech stack
        stack_match = re.search(r'##\s+Tech\s+Stack\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if stack_match:
            stack_text = stack_match.group(1)
            tech_stack = re.findall(r'[-*]\s+(.+)', stack_text)
            constraints["tech_stack"] = tech_stack
        
        return constraints
    
    def _parse_technical_requirements(self, content: str) -> Dict[str, Any]:
        """Extract technical requirements from Markdown content"""
        requirements = {}
        
        # Extract architecture requirements
        arch_match = re.search(r'##\s+Architecture\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if arch_match:
            arch_text = arch_match.group(1)
            requirements["architecture"] = re.findall(r'[-*]\s+(.+)', arch_text)
        
        # Extract deployment requirements
        deploy_match = re.search(r'##\s+Deployment\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if deploy_match:
            deploy_text = deploy_match.group(1)
            requirements["deployment"] = re.findall(r'[-*]\s+(.+)', deploy_text)
        
        return requirements
    
    def _parse_bmad_settings(self, content: str) -> Dict[str, Any]:
        """Extract BMAD-specific settings from Markdown content"""
        bmad_settings = {}
        
        # Extract BMAD configuration section
        bmad_match = re.search(r'##\s+BMAD\s+Configuration\s*\n(.*?)(?=\n##|\n---|\Z)', content, re.DOTALL | re.IGNORECASE)
        if bmad_match:
            bmad_text = bmad_match.group(1)
            
            # Extract IDE preference
            ide_match = re.search(r'IDE:\s*(.+)', bmad_text, re.IGNORECASE)
            if ide_match:
                bmad_settings["preferred_ide"] = ide_match.group(1).strip()
            
            # Extract expansion packs
            expansion_match = re.search(r'Expansion\s+Packs?:\s*\n(.*?)(?=\n\w|\Z)', bmad_text, re.DOTALL | re.IGNORECASE)
            if expansion_match:
                expansion_text = expansion_match.group(1)
                expansions = re.findall(r'[-*]\s+(.+)', expansion_text)
                bmad_settings["expansion_packs"] = expansions
        
        # Default settings if not specified
        if "preferred_ide" not in bmad_settings:
            bmad_settings["preferred_ide"] = "claude-code"
        
        if "expansion_packs" not in bmad_settings:
            bmad_settings["expansion_packs"] = []
        
        return bmad_settings

# --- BMAD Installation Manager ---

class BMADInstaller:
    """Handles BMAD-METHOD installation and initialization"""
    
    def __init__(self, project_dir: Path, config: Dict[str, Any]):
        self.project_dir = project_dir
        self.config = config
        self.bmad_dir = project_dir / ".bmad-core"
    
    def is_bmad_installed(self) -> bool:
        """Check if BMAD is already installed in the project directory"""
        return self.bmad_dir.exists() and (self.bmad_dir / "core-config.yaml").exists()
    
    async def install_bmad_method(self) -> bool:
        """Install BMAD-METHOD using npx"""
        try:
            bmad_logger.logger.info(f"Installing BMAD-METHOD in {self.project_dir}")
            
            # Check if Node.js is available
            try:
                result = subprocess.run(["node", "--version"], capture_output=True, text=True, timeout=10)
                if result.returncode != 0:
                    bmad_logger.logger.error("Node.js not found. BMAD-METHOD requires Node.js")
                    return False
                bmad_logger.logger.info(f"Node.js version: {result.stdout.strip()}")
            except (subprocess.TimeoutExpired, FileNotFoundError):
                bmad_logger.logger.error("Node.js not available. Cannot install BMAD-METHOD")
                return False
            
            # Install BMAD-METHOD using npx
            install_cmd = ["npx", "bmad-method@latest", "install", "--full", "--directory", str(self.project_dir)]
            
            # Add IDE configuration
            bmad_settings = self.config.get("bmad_settings", {})
            preferred_ide = bmad_settings.get("preferred_ide", "claude-code")
            install_cmd.extend(["--ide", preferred_ide])
            
            # Add expansion packs if specified
            expansion_packs = bmad_settings.get("expansion_packs", [])
            if expansion_packs:
                install_cmd.extend(["--expansion-packs"] + expansion_packs)
            
            bmad_logger.logger.info(f"Running BMAD install command: {' '.join(install_cmd)}")
            
            # Run the installation
            process = subprocess.Popen(
                install_cmd,
                cwd=self.project_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            
            # Monitor the process
            stdout, stderr = process.communicate(timeout=300)  # 5 minute timeout
            
            if process.returncode == 0:
                bmad_logger.logger.info("BMAD-METHOD installation completed successfully")
                bmad_logger.log_bmad_installation(str(self.project_dir), True, "Installation successful")
                return True
            else:
                error_msg = f"BMAD installation failed with return code {process.returncode}"
                if stderr:
                    error_msg += f"\nError output: {stderr}"
                bmad_logger.logger.error(error_msg)
                bmad_logger.log_bmad_installation(str(self.project_dir), False, error_msg)
                return False
                
        except subprocess.TimeoutExpired:
            bmad_logger.logger.error("BMAD installation timed out after 5 minutes")
            bmad_logger.log_bmad_installation(str(self.project_dir), False, "Installation timeout")
            return False
        except Exception as e:
            error_msg = f"Error during BMAD installation: {e}"
            bmad_logger.logger.error(error_msg)
            bmad_logger.log_bmad_installation(str(self.project_dir), False, error_msg)
            return False
    
    def configure_bmad_for_claude_code(self) -> bool:
        """Configure BMAD to work with Claude Code CLI"""
        try:
            core_config_path = self.bmad_dir / "core-config.yaml"
            if not core_config_path.exists():
                bmad_logger.logger.error("BMAD core-config.yaml not found")
                return False
            
            # Read the current configuration
            import yaml
            with open(core_config_path, 'r') as f:
                core_config = yaml.safe_load(f)
            
            # Update configuration for Claude Code integration
            if 'agents' not in core_config:
                core_config['agents'] = {}
            
            # Add Claude Code as the primary agent administrator
            core_config['agents']['primary_administrator'] = 'claude-code'
            core_config['agents']['claude_code_integration'] = True
            
            # Add project-specific settings from our config
            project_details = self.config.get("project_details", {})
            if project_details.get("name"):
                core_config['project_name'] = project_details["name"]
            if project_details.get("description"):
                core_config['project_description'] = project_details["description"]
            
            # Write back the updated configuration
            with open(core_config_path, 'w') as f:
                yaml.dump(core_config, f, default_flow_style=False, sort_keys=False)
            
            bmad_logger.logger.info("Successfully configured BMAD for Claude Code integration")
            return True
            
        except Exception as e:
            bmad_logger.logger.error(f"Error configuring BMAD for Claude Code: {e}")
            return False

# --- Helper Functions ---

def load_config(config_path: str = "initProject.md") -> Dict[str, Any]:
    """Loads the Markdown configuration file with enhanced error handling."""
    config_file = Path(config_path)
    
    if not config_file.exists():
        bmad_logger.logger.error(f"Configuration file not found at {config_path}")
        # Try alternative locations
        alternative_paths = [
            Path("initProject.md"),
            Path("project-init.md"),
            Path("project.md"),
            Path(".claude/initProject.md"),
            Path("docs/initProject.md")
        ]
        
        for alt_path in alternative_paths:
            if alt_path.exists():
                bmad_logger.logger.info(f"Found alternative config at {alt_path}")
                config_file = alt_path
                break
        else:
            bmad_logger.logger.error("No Markdown configuration file found in any location")
            sys.exit(1)
    
    try:
        parser = MarkdownConfigParser(str(config_file))
        config = parser.parse()
        bmad_logger.logger.info(f"Loaded Markdown configuration from {config_file}")
        return config
    except Exception as e:
        bmad_logger.logger.error(f"Error parsing Markdown configuration: {e}")
        sys.exit(1)

def parse_hook_input() -> Dict[str, Any]:
    """Parse hook input data from stdin with enhanced structure."""
    try:
        # Try to parse as JSON first (standard hook format)
        stdin_content = sys.stdin.read().strip()
        
        if not stdin_content:
            bmad_logger.logger.warning("No input received from stdin")
            return {"cli_output": "", "hook_event_name": "unknown"}
        
        # Check if it's JSON hook data
        try:
            hook_data = json.loads(stdin_content)
            bmad_logger.logger.info(f"Parsed hook data: {hook_data.get('hook_event_name', 'unknown')}")
            return hook_data
        except json.JSONDecodeError:
            # Fallback to treating as plain CLI output
            bmad_logger.logger.info("Treating input as plain CLI output")
            return {
                "cli_output": stdin_content,
                "hook_event_name": "cli_interaction",
                "session_id": f"session_{int(time.time())}",
                "cwd": os.getcwd()
            }
    
    except Exception as e:
        bmad_logger.logger.error(f"Error parsing hook input: {e}")
        return {"cli_output": "", "hook_event_name": "error"}

def generate_enhanced_system_prompt(config: Dict[str, Any], hook_data: Dict[str, Any]) -> str:
    """Generate enhanced system prompt with hook context and Markdown config data."""
    project_details = config.get("project_details", {})
    constraints = config.get("constraints", {})
    technical_requirements = config.get("technical_requirements", {})
    bmad_settings = config.get("bmad_settings", {})
    
    prompt = f"""You are an AI assistant for the '{project_details.get("name", "Unnamed Project")}' project.

Project Description: {project_details.get("description", "No description provided.")}

Hook Context:
- Event: {hook_data.get("hook_event_name", "unknown")}
- Session: {hook_data.get("session_id", "unknown")}
- Tool: {hook_data.get("tool_name", "N/A")}
- Working Directory: {hook_data.get("cwd", "unknown")}

Your task is to act as an expert decision-maker, guiding the project planning process according to the BMAD methodology. You will be presented with a series of choices from the Claude Code CLI. 

CRITICAL: Your response must end with exactly one number (1-9) corresponding to your choice. Provide your reasoning first, then end with just the number.

Project Constraints:
"""

    # Add constraints with better formatting
    compute = constraints.get("compute_resources", [])
    if compute:
        prompt += "\nCompute Resources:\n"
        for resource in compute:
            prompt += f"  • {resource}\n"

    tech_stack = constraints.get("tech_stack", [])
    if tech_stack:
        prompt += "\nTech Stack:\n"
        for tech in tech_stack:
            prompt += f"  • {tech}\n"

    budget = constraints.get("budget", {})
    if budget:
        prompt += "\nBudget Constraints:\n"
        prompt += f"  • Total Budget: ${budget.get('total_usd', 'N/A'):,}\n"
        prompt += f"  • Timeline: {budget.get('timeline_weeks', 'N/A')} weeks\n"

    # Add technical requirements
    architecture = technical_requirements.get("architecture", [])
    if architecture:
        prompt += "\nArchitecture Requirements:\n"
        for req in architecture:
            prompt += f"  • {req}\n"

    deployment = technical_requirements.get("deployment", [])
    if deployment:
        prompt += "\nDeployment Requirements:\n"
        for req in deployment:
            prompt += f"  • {req}\n"

    # Add BMAD settings
    prompt += f"\nBMAD Configuration:\n"
    prompt += f"  • Preferred IDE: {bmad_settings.get('preferred_ide', 'claude-code')}\n"
    
    expansion_packs = bmad_settings.get("expansion_packs", [])
    if expansion_packs:
        prompt += f"  • Expansion Packs: {', '.join(expansion_packs)}\n"

    prompt += "\nBMAD Methodology Guidelines:\n"
    prompt += "  • Prioritize proper planning and requirements gathering\n"
    prompt += "  • Consider technical constraints and resource limitations\n"
    prompt += "  • Align decisions with project timeline and budget\n"
    prompt += "  • Choose options that support iterative development\n"
    prompt += "  • Leverage BMAD expansion packs when applicable\n"
    
    prompt += "\nRemember: Provide your reasoning, then end with ONLY the number of your choice (1-9)."
    
    return prompt

async def get_enhanced_claude_decision(
    system_prompt: str, 
    hook_data: Dict[str, Any], 
    api_key: str
) -> tuple[str, str]:
    """Get decision from Claude SDK with enhanced error handling and reasoning extraction."""
    
    start_time = time.time()
    bmad_logger.logger.info("Requesting decision from Claude SDK...")
    
    # Set API key
    os.environ["ANTHROPIC_API_KEY"] = api_key
    
    # Configure Claude options
    options = ClaudeCodeOptions(
        system_prompt=system_prompt,
        model="claude-3-5-sonnet-20241022",
        max_turns=1,
        max_thinking_tokens=2000,
    )
    
    # Prepare the prompt
    cli_output = hook_data.get("cli_output", "")
    if hook_data.get("tool_input"):
        cli_output += f"\n\nTool Input: {json.dumps(hook_data['tool_input'], indent=2)}"
    
    full_prompt = f"""Analyze the following Claude Code CLI output and make the best decision based on the project constraints and BMAD methodology.

CLI Output:
---
{cli_output}
---

Provide your reasoning and analysis, then end your response with ONLY the number of your choice."""

    decision_text = ""
    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(full_prompt)
            async for message in client.receive_response():
                if hasattr(message, "content"):
                    for block in message.content:
                        if hasattr(block, "text"):
                            decision_text += block.text

        execution_time = time.time() - start_time
        bmad_logger.logger.info(f"Received response in {execution_time:.2f} seconds")
        
        # Extract decision number and reasoning
        decision_number = extract_decision_number(decision_text)
        reasoning = decision_text.strip()
        
        return decision_number, reasoning

    except Exception as e:
        execution_time = time.time() - start_time
        bmad_logger.logger.error(f"Error interacting with Claude SDK: {e}")
        
        # Enhanced fallback logic
        fallback_decision = get_fallback_decision(hook_data, cli_output)
        reasoning = f"Fallback decision due to API error: {e}"
        
        return fallback_decision, reasoning

def extract_decision_number(decision_text: str) -> str:
    """Extract decision number from Claude's response with enhanced parsing."""
    
    # Look for number at the end of the response
    lines = decision_text.strip().split('\n')
    for line in reversed(lines):
        line = line.strip()
        if line and line.isdigit() and 1 <= int(line) <= 9:
            return line
    
    # Look for any digit in the text
    for char in decision_text:
        if char.isdigit() and 1 <= int(char) <= 9:
            return char
    
    bmad_logger.logger.warning("No valid decision number found in response. Defaulting to 1.")
    return "1"

def get_fallback_decision(hook_data: Dict[str, Any], cli_output: str) -> str:
    """Intelligent fallback decision based on context."""
    
    cli_lower = cli_output.lower()
    
    # BMAD methodology priorities
    if "prd" in cli_lower or "requirements" in cli_lower:
        return "1"  # Prioritize requirements gathering
    elif "architecture" in cli_lower or "design" in cli_lower:
        return "2"  # Architecture comes after requirements
    elif "development" in cli_lower or "coding" in cli_lower:
        return "3"  # Development after planning
    elif "test" in cli_lower or "qa" in cli_lower:
        return "4"  # Testing after development
    else:
        return "1"  # Default to first option

def inject_enhanced_response(decision: str, hook_data: Dict[str, Any]):
    """Inject response with enhanced logging and monitoring."""
    
    try:
        bmad_logger.logger.info(f"Injecting decision: {decision}")
        
        # Log the injection for audit trail
        injection_record = {
            "timestamp": datetime.now().isoformat(),
            "session_id": hook_data.get("session_id"),
            "decision": decision,
            "hook_event": hook_data.get("hook_event_name"),
            "injection_method": "stdout"
        }
        
        bmad_logger.logger.info(f"INJECTION: {json.dumps(injection_record)}")
        
        # Output the decision
        print(decision)
        
    except Exception as e:
        bmad_logger.logger.error(f"Failed to inject response: {e}")
        # Still try to output something
        print("1")
        sys.exit(1)

# --- Main Execution ---

async def main():
    """Enhanced main function with BMAD installation and Markdown config support."""
    
    try:
        start_time = time.time()
        bmad_logger.logger.info("Starting BMAD Automator Enhanced with Markdown Config Support")
        
        # Load Markdown configuration
        config = load_config()
        
        # Check if we're in new project initialization mode
        current_dir = Path.cwd()
        bmad_installer = BMADInstaller(current_dir, config)
        
        # Install BMAD if not present
        if not bmad_installer.is_bmad_installed():
            bmad_logger.logger.info("BMAD not found in current directory. Installing...")
            success = await bmad_installer.install_bmad_method()
            if success:
                bmad_installer.configure_bmad_for_claude_code()
            else:
                bmad_logger.logger.warning("BMAD installation failed, continuing with decision making")
        else:
            bmad_logger.logger.info("BMAD already installed in current directory")
        
        # Parse hook input
        hook_data = parse_hook_input()
        
        # Check for API key
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            bmad_logger.logger.error("ANTHROPIC_API_KEY environment variable not set")
            sys.exit(1)
        
        # Generate enhanced system prompt
        system_prompt = generate_enhanced_system_prompt(config, hook_data)
        
        # Get decision from Claude SDK
        decision, reasoning = await get_enhanced_claude_decision(system_prompt, hook_data, api_key)
        
        # Log the decision
        execution_time = time.time() - start_time
        bmad_logger.log_decision(hook_data, decision, reasoning, execution_time)
        
        # Inject the response
        inject_enhanced_response(decision, hook_data)
        
        bmad_logger.logger.info(f"BMAD Automator completed successfully in {execution_time:.2f} seconds")
        
    except Exception as e:
        bmad_logger.logger.error(f"Fatal error in main execution: {e}")
        print("1")  # Emergency fallback
        sys.exit(1)

if __name__ == "__main__":
    # Ensure API key is set via environment variable
    if not os.environ.get("ANTHROPIC_API_KEY"):
        bmad_logger.logger.error("ANTHROPIC_API_KEY environment variable not set")
        print("Error: ANTHROPIC_API_KEY environment variable is required")
        sys.exit(1)
    
    asyncio.run(main())
